env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm64
    main: main.go
    binary: bizfly
    hooks:
      pre: make build
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
universal_binaries:
  - name_template: 'bizfly'
    replace: true
    hooks:
      pre: make build
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip
source:
  enabled: true
  name_template: '{{ .ProjectName }}'
  format: 'tar'
release:
  github:
    owner: bizflycloud
    name: bizflyctl
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"

brews:
  - homepage: 'https://github.com/bizflycloud/bizflyctl'
    description: ' Command Line for Bizfly Cloud.'
    directory: Formula
    commit_author:
      name: Tung Son Do
      email: tungds@bizflycloud.vn
    repository:
      owner: bizflycloud
      name: bizflyctl

